### ISSUE TITLE
Pre-RFC: IDE integration for Haskell testing frameworks

### ISSUE THREAD

**Issue by santiweight** [haskellfoundation/tech-proposals#45]
**NOTE** This is a pre-RFC, intended to get a first impression perspective on the validity of my solution to a problem in the Haskell ecosystem. If the response is something like "this seems like a good direction", then I'll go ahead and clean the PR up and put it out on discourse etc. In other words: feel free to simply glance :)

I'm currently working on a proposal for integrating various testing frameworks' output format so that they can be used in IDEs that support Haskell.

Feedback is very helpful, especially from testing framework maintainers, so that I can better understand what use cases are most important and we don't miss anything important.

[Rendered](https://github.com/santiweight/tech-proposals/blob/ide-test-integration/proposals/accepted/50-ide-test-integration.md)

**Comment by david-christiansen** [comment]
Thanks for submitting a proposal!

Before this issue gathers discussion and comments, would you mind restructuring this as a pull request? That'll help us follow our usual workflow. Instructions are here: https://github.com/haskellfoundation/tech-proposals/blob/main/proposals/PROPOSALS.md#proposal

**Comment by santiweight** [comment]
Oh - I was avoiding doing so until it was more ready. I was hoping to get a pair of eyes to check it was not awful before putting the effort into cleaning it up to a better standard.

I realize I didn't make that clear in the issue 😅

**Comment by david-christiansen** [comment]
I think that it is already not awful, and perfectly fine to have as a PR as it currently stands. It's an expected part of the process to revise the text in the PR in response to the discussion. What I'd like to avoid is having discussion split between Discourse, an issue, and the PR - it's much easier to follow if the PR has the whole history.

That OK with you?

**Comment by santiweight** [comment]
Yep: I'll put it up for RFC

**Comment by david-christiansen** [comment]
Thanks!

**Comment by santiweight** [comment]
https://github.com/haskellfoundation/tech-proposals/pull/46

Closing :) Thanks for the guidance David!

**Comment by david-christiansen** [comment]
Thank you!
